version: '3.1'

services:
  api:
    image: 'xylo-api'
    expose:
      - 8080/tcp
    ports:
      - 4001:8080
    build: 'apps/api/.'
    environment:
      NODE_ENV: "development"
      PORT: 8080
  app:
    depends_on:
      - api
    image: 'xylo-app'
    build: '.'
    ports:
      - 3000:80
