version: "3.8"

networks:
  corp:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: ./
      cache_from:
        - gcr.io/xylo-328123/xylo
      dockerfile: ./apps/api/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: api:nx-dev
    ports:
      - 8080:8080
    environment:
      NODE_ENV: "development"
      PORT: 8080
    networks:
      - corp
    restart: on-failure
    command: yarn gc-start

  xylo:
    container_name: xylo
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/xylo/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: xylo:nx-dev
    ports:
      - 4900:4200
    environment:
      NODE_ENV: "development"
      PORT: 4900
    networks:
      - corp
    restart: on-failure